name: Atualizar Badge de Visitas
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pegar número de visitas
        run: |
          VISITS=$(curl -s "https://komarev.com/ghpvc/?username=fernandosmcode" | tr -d '\n')
          echo "Número de visitas: $VISITS"
          cat <<EOF > visitas.json
          {
            "schemaVersion": 1,
            "label": "Visitas",
            "message": "$VISITS",
            "color": "000000",
            "labelColor": "FFFFFF"
          }

      - name: Commit e push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add visitas.json
          git commit -m "Atualiza badge de visitas" || echo "Nada para commitar"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
